package frontend.GUIClasses.Pages;

import frontend.Client;
import frontend.GUIClasses.Styling.BackgroundPanel;
import frontend.GUIClasses.Styling.CustomFont;

import javax.swing.*;
import java.awt.*;
import java.util.LinkedHashMap;
import java.util.Map;

public class GamePage {
    private final Client client;
    private JPanel playerCardsPanel;
    private JPanel dealerCardsPanel;
    private JLabel playerTotalLabel;
    private JLabel dealerTotalLabel;
    private JLabel balanceLabel;
    private JLabel resultLabel;
    private JPanel ghostPanel;


    private final Map<String, JPanel> otherCardPanels  = new LinkedHashMap<>();
    private final Map<String, JLabel> otherTotalLabels = new LinkedHashMap<>();
    private final Map<String, JLabel> otherNameLabels  = new LinkedHashMap<>();
    private JPanel otherPlayersRow;

    // Win, Loss, or Draw notification
    public void setResultLabelText(String text, Color color)
    {
        this.resultLabel.setText(text);
        this.resultLabel.setForeground(color);
        resultLabel.setFont(new Font ("Lucida Handwriting", Font.BOLD, 70));
        resultLabel.setOpaque(true);
        resultLabel.setBackground(new Color(0, 0, 0, 180));
        resultLabel.setBorder(BorderFactory.createEmptyBorder(10, 40, 10, 40));
    }

    // Displays the player's account balance
    public void setBalanceLabel(String text)
    {
        this.balanceLabel.setText("Balance: $" + text);
        balanceLabel.revalidate();
        SwingUtilities.invokeLater(() -> {
            Component ghost = ((BorderLayout)balanceLabel.getParent().getParent().getLayout())
                    .getLayoutComponent(BorderLayout.WEST);
            if (ghost != null) {
                ghost.setPreferredSize(new Dimension(balanceLabel.getParent().getPreferredSize().width, 0));
                ghost.getParent().revalidate();
            }
        });
    }

    public GamePage(Client client) {
        this.client = client;
    }

    // Resets cards and card totals on the table for next round
    public void resetTable()
    {
        dealerCardsPanel.removeAll();
        playerCardsPanel.removeAll();
        dealerTotalLabel.setText("Total: 0");
        playerTotalLabel.setText("Total: 0");
        resultLabel.setText(" ");
        dealerCardsPanel.revalidate();
        dealerCardsPanel.repaint();
        playerCardsPanel.revalidate();
        playerCardsPanel.repaint();
        resultLabel.setOpaque(false);
        resultLabel.setBorder(null);
    }

    public JPanel createGamePanel() {
        // Table.png image generated by Gemini
        BackgroundPanel backgroundPanel = new BackgroundPanel("Table.png");
        backgroundPanel.setLayout(new BorderLayout());

        JPanel gamePanel = new JPanel();
        gamePanel.setOpaque(false);
        gamePanel.setLayout(new BoxLayout(gamePanel, BoxLayout.Y_AXIS));

        resultLabel = new JLabel(" ");
        resultLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        dealerCardsPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, -120, 0));
        dealerCardsPanel.setOpaque(false);

        dealerTotalLabel = new JLabel();
        dealerTotalLabel.setFont(CustomFont.newFont(28));
        dealerTotalLabel.setForeground(Color.WHITE);
        dealerTotalLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        dealerTotalLabel.setOpaque(true);
        dealerTotalLabel.setBackground(new Color(0, 0, 0, 140));
        dealerTotalLabel.setBorder(BorderFactory.createEmptyBorder(6, 12, 6, 12));

        playerCardsPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, -120, 0));
        playerCardsPanel.setOpaque(false);
        playerCardsPanel.add(new JLabel("Player"));

        playerTotalLabel = new JLabel();
        playerTotalLabel.setFont(CustomFont.newFont(28));
        playerTotalLabel.setForeground(Color.WHITE);
        playerTotalLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        playerTotalLabel.setOpaque(true);
        playerTotalLabel.setBackground(new Color(0, 0, 0, 140));
        playerTotalLabel.setBorder(BorderFactory.createEmptyBorder(6, 12, 6, 12));

        balanceLabel = new JLabel("Balance: $0");
        balanceLabel.setFont(CustomFont.newFont(28));
        balanceLabel.setForeground(Color.WHITE);
        balanceLabel.setOpaque(true);
        balanceLabel.setBackground(new Color(0, 0, 0, 140));
        balanceLabel.setBorder(BorderFactory.createEmptyBorder(8, 14, 8, 14));

        JPanel balanceWrapper = new JPanel(new BorderLayout());
        balanceWrapper.setOpaque(false);
        balanceWrapper.setBorder(BorderFactory.createEmptyBorder(0, 0, 25, 25));
        balanceWrapper.setPreferredSize(null);
        balanceWrapper.add(balanceLabel, BorderLayout.SOUTH);

        // acts as counterweight to balancelabel, centering the cards
        ghostPanel = new JPanel();
        ghostPanel.setOpaque(false);
        SwingUtilities.invokeLater(() -> { // adjust counterweight panel based on balancelabel size
            int w = balanceWrapper.getPreferredSize().width;
            ghostPanel.setPreferredSize(new Dimension(w, 0));
            ghostPanel.revalidate();
        });

        gamePanel.add(Box.createVerticalGlue());
        gamePanel.add(Box.createVerticalStrut(20));
        gamePanel.add(dealerCardsPanel);
        gamePanel.add(Box.createVerticalStrut(4));
        gamePanel.add(dealerTotalLabel);

        gamePanel.add(Box.createVerticalStrut(40));
        gamePanel.add(resultLabel);
        gamePanel.add(Box.createVerticalStrut(40));

        gamePanel.add(playerCardsPanel);
        gamePanel.add(Box.createVerticalStrut(0));
        gamePanel.add(playerTotalLabel);
        gamePanel.add(Box.createVerticalStrut(60));
        gamePanel.add(Box.createVerticalGlue());

        backgroundPanel.add(balanceWrapper, BorderLayout.EAST);
        JPanel buttonPanel = new JPanel();
        buttonPanel.setOpaque(false);

        JButton hitButton = new JButton("Hit");
        JButton standButton = new JButton("Stand");

        hitButton.setFont(CustomFont.newFont(25f));
        standButton.setFont(CustomFont.newFont(25f));

        hitButton.setMaximumSize(new Dimension(220, 45));
        standButton.setMaximumSize(new Dimension(220, 45));

        hitButton.addActionListener(e -> {
            client.sendMessage("hit");
        });

        standButton.addActionListener(e -> {
            client.sendMessage("stay");
        });

        buttonPanel.add(hitButton);
        buttonPanel.add(standButton);

        JScrollPane scrollPane = new JScrollPane(gamePanel);
        scrollPane.setBorder(null);
        scrollPane.setOpaque(false);
        scrollPane.getViewport().setOpaque(false);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        backgroundPanel.add(scrollPane, BorderLayout.CENTER);
        backgroundPanel.add(buttonPanel, BorderLayout.SOUTH);
        backgroundPanel.add(balanceWrapper, BorderLayout.EAST);
        backgroundPanel.add(ghostPanel, BorderLayout.WEST);

        return backgroundPanel;
    }

    // handles server response for game status
    public void updateGameDisplay(String data) {

        try {
            // Expected format: "DealerTotal:DCard1,DCard2|PlayerTotal:PCard1,PCard2"
            String[] serverData = data.split("\\|");
            String[] dealerData = serverData[0].split(":");
            String[] playerData = serverData[1].split(":");
            String balanceData = serverData[2];
            balanceLabel.setText("Balance: $" + balanceData);

            dealerTotalLabel.setText("Total: " + dealerData[0]);
            playerTotalLabel.setText("Total: " + playerData[0]);

            dealerCardsPanel.removeAll();
            if (dealerData.length > 1 && !dealerData[1].isEmpty()) {
                for (String cardStr : dealerData[1].split(",")) {
                    dealerCardsPanel.add(createCardLabel(cardStr));
                }
            }

            playerCardsPanel.removeAll();
            if (playerData.length > 1 && !playerData[1].isEmpty()) {
                for (String cardStr : playerData[1].split(",")) {
                    playerCardsPanel.add(createCardLabel(cardStr));
                }
            }

            dealerCardsPanel.revalidate();
            dealerCardsPanel.repaint();
            playerCardsPanel.revalidate();
            playerCardsPanel.repaint();

        } catch (Exception e) {
            System.err.println("Error parsing update string from server: " + data);
        }
    }

    // Creates card visual through getting appropriate card file.
    private JLabel createCardLabel(String card) {
        card = card.trim();
        String fileName = "CardImages/" + card + ".png";
        java.net.URL imageUrl = getClass().getClassLoader().getResource(fileName);

        if (imageUrl == null) {
            JLabel fallback = new JLabel(fileName);
            fallback.setForeground(Color.WHITE);
            return fallback;
        }

        ImageIcon icon = new ImageIcon(imageUrl);
        Image scaled = icon.getImage().getScaledInstance(180, 160, Image.SCALE_SMOOTH);
        return new JLabel(new ImageIcon(scaled));
    }
}
