package frontend.GUIClasses.pages;

import frontend.Client;
import frontend.GUIClasses.styling.BackgroundMusic;
import frontend.GUIClasses.styling.BackgroundPanel;
import frontend.GUIClasses.styling.CustomFont;

import javax.swing.*;
import java.awt.*;

public class LobbyPage {
    /** FIELDS --------------------------------------------------------------------------------------------------- **/
    private final Client client;
    private final CardLayout cardLayout;
    private final JPanel mainPanel;
    private final CustomFont customFont = new CustomFont();
    private JButton addFundsButton;
    private JLabel userBalanceLabel;

    private BackgroundMusic backgroundMusic;
    private JButton muteMusicButton;
    private JButton logOffButton;

    private JScrollPane scrollTableList;
    private JPanel activeTablesPanel;
    private JLabel clickRefreshLabel;
    private JPanel tableListPanel;

    /** CONSTRUCTOR --------------------------------------------------------------------------------------------------- **/
    public LobbyPage(Client client, CardLayout cardLayout, JPanel mainPanel, BackgroundMusic backgroundMusic)
    {
        this.client = client;
        this.cardLayout = cardLayout;
        this.mainPanel = mainPanel;
        this.backgroundMusic = backgroundMusic;
    }

    /** PAGE BUILDER --------------------------------------------------------------------------------------------------- **/

    /** Builds the start menu UI
     * Initializes components and actions
     * @return JPanel start menu panel for card layout
     **/
    public JPanel createStartMenu() {
        // Table Start.png generated by Gemini
        JPanel startPageWrapper = new JPanel(new BorderLayout());
        JPanel wallpaper = new BackgroundPanel("wallpaper.png");
        wallpaper.setPreferredSize(new Dimension(900,800));

        // Table options
        JPanel startMenuPanel = new BackgroundPanel("menu_wallpaper.png");
        startMenuPanel.setLayout(new BoxLayout(startMenuPanel, BoxLayout.Y_AXIS));
        startMenuPanel.setPreferredSize(new Dimension(300,800));
        startMenuPanel.setBackground(Color.WHITE);

        JLabel titleLabel = new JLabel("OTech Blackjack");
        titleLabel.setFont(customFont.bold(25));
        titleLabel.setForeground(new Color(0, 60, 113));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        Dimension buttonSize = new Dimension(250, 40);
        JButton createTableButton = new JButton("Create New Table");
        createTableButton.setFont(customFont.regular(20));
        createTableButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        createTableButton.setPreferredSize(buttonSize);
        createTableButton.setMaximumSize(buttonSize);
        createTableButton.setMinimumSize(buttonSize);
        createTableButton.addActionListener(e ->
        {
            client.sendMessage("NEW_TABLE");
        });

        // Live tables list components
        JButton refreshTablesButton = new JButton("Refresh Tables");
        refreshTablesButton.setFont(customFont.regular(20));
        refreshTablesButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        refreshTablesButton.setPreferredSize(buttonSize);
        refreshTablesButton.setMaximumSize(buttonSize);
        refreshTablesButton.setMinimumSize(buttonSize);
        refreshTablesButton.addActionListener(e -> getTableList());

        activeTablesPanel = new JPanel();
        activeTablesPanel.setLayout(new BoxLayout(activeTablesPanel, BoxLayout.Y_AXIS));
        activeTablesPanel.setOpaque(false);

        clickRefreshLabel = new JLabel("<html><center>No live tables.<br>Please click refresh tables.</center></html>");
        clickRefreshLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        clickRefreshLabel.setHorizontalAlignment(SwingConstants.CENTER);
        clickRefreshLabel.setFont(customFont.regular(20));

        tableListPanel = new JPanel();
        tableListPanel.setLayout(new BoxLayout(tableListPanel, BoxLayout.Y_AXIS));
        tableListPanel.setOpaque(false);

        tableListPanel.add(clickRefreshLabel);
        tableListPanel.add(Box.createVerticalStrut(10));
        tableListPanel.add(activeTablesPanel);

        scrollTableList = new JScrollPane(tableListPanel);
        scrollTableList.setPreferredSize(new Dimension(250, 350));
        scrollTableList.setMaximumSize(new Dimension(250, 350));
        scrollTableList.setMinimumSize(new Dimension(250, 350));
        scrollTableList.getVerticalScrollBar().setUnitIncrement(12);
        scrollTableList.setOpaque(false);
        scrollTableList.setBorder(BorderFactory.createEmptyBorder());
        scrollTableList.getViewport().setOpaque(false);
        scrollTableList.getViewport().setBorder(null);

        client.sendMessage("TABLE_LIST");

        // Account balance management
        userBalanceLabel = new JLabel("Account Balance: ");
        userBalanceLabel.setFont(customFont.bold(20));
        userBalanceLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        addFundsButton = new JButton("Add Funds");
        addFundsButton.setFont(customFont.regular(20));
        addFundsButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        addFundsButton.setPreferredSize(buttonSize);
        addFundsButton.setMaximumSize(buttonSize);
        addFundsButton.setMinimumSize(buttonSize);

        addFundsButton.addActionListener(e -> {
            String input = JOptionPane.showInputDialog(mainPanel, "Enter amount to add:", "Add Funds", JOptionPane.PLAIN_MESSAGE);
            if (input != null && !input.trim().isEmpty()) {
                try {
                    int amount = Integer.parseInt(input.trim());
                    if (amount > 0) {
                        client.sendMessage("ADD_FUNDS " + amount);
                    } else {
                        JOptionPane.showMessageDialog(mainPanel, "Please enter a valid positive amount.");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(mainPanel, "Invalid amount. Please enter a whole number.");
                }
            }
        });

        muteMusicButton = new JButton("Music Off");
        backgroundMusic.registerButton(muteMusicButton);
        muteMusicButton.setFont(customFont.regular(20f));
        muteMusicButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        muteMusicButton.setPreferredSize(buttonSize);
        muteMusicButton.setMaximumSize(buttonSize);
        muteMusicButton.setMinimumSize(buttonSize);

        muteMusicButton.addActionListener(e -> {
            boolean isMuted = backgroundMusic.toggleMute();
            if (isMuted)
            {
                backgroundMusic.stopMusic();
            } else
            {
                backgroundMusic.playMusic("src/main/resources/music/BlackJackBGM.wav");
            }
        });

        logOffButton = new JButton("Log Off");
        logOffButton.setFont(customFont.regular(20));
        logOffButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        logOffButton.setPreferredSize(buttonSize);
        logOffButton.setMaximumSize(buttonSize);
        logOffButton.setMinimumSize(buttonSize);
        logOffButton.addActionListener(e -> { client.sendMessage("LOGOUT");});

        // Assemble start menu
        startMenuPanel.add(Box.createVerticalStrut(30));
        startMenuPanel.add(titleLabel);

        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(createTableButton);

        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(refreshTablesButton);

        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(scrollTableList);

        startMenuPanel.add(userBalanceLabel);
        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(addFundsButton);
        startMenuPanel.add(Box.createVerticalStrut(10));
        startMenuPanel.add(muteMusicButton);
        startMenuPanel.add(Box.createVerticalStrut(10));
        startMenuPanel.add(logOffButton);
        startMenuPanel.add(Box.createVerticalGlue());

        startPageWrapper.add(wallpaper, BorderLayout.WEST);
        startPageWrapper.add(startMenuPanel, BorderLayout.EAST);
        return startPageWrapper;
    }

    /** HELPER METHODS --------------------------------------------------------------------------------------------------- **/

    /** Parses and displays active tables
     * Creates join buttons dynamically
     * @param data The data being parsed
     **/
    public void tableList(String data)
    {
        String[] parts = data.split("\\|");

        if (parts.length < 4)
        {
            if (activeTablesPanel.getComponentCount() == 0) {
                clickRefreshLabel.setVisible(true);
            }
        }
        else
        {
            clickRefreshLabel.setVisible(false);

            String tableId = parts[1];
            String numClients = parts[2];
            String hasRoom = parts[3];

            Dimension buttonSize = new Dimension(250, 40);
            JButton joinButton = new JButton("Join Table " + tableId + " (" + numClients + "/3)");
            joinButton.setFont(customFont.regular(20));
            joinButton.setAlignmentX(Component.CENTER_ALIGNMENT);
            joinButton.setPreferredSize(buttonSize);
            joinButton.setMaximumSize(buttonSize);
            joinButton.setMinimumSize(buttonSize);
            joinButton.setEnabled(hasRoom.equals("Y"));

            joinButton.addActionListener(e -> joinTable(tableId));

            activeTablesPanel.add(joinButton);
            activeTablesPanel.add(Box.createVerticalStrut(10));
        }

        activeTablesPanel.revalidate();
        activeTablesPanel.repaint();
        tableListPanel.revalidate();
        tableListPanel.repaint();
    }

    /** Sends request to join a table
     *@param tableId The ID of the table to be joined in
     **/
    public void joinTable(String tableId)
    {
        client.sendMessage("JOIN_TABLE " + tableId);
    }

    /** Refreshes and requests table list **/
    public void getTableList() {
        activeTablesPanel.removeAll();
        clickRefreshLabel.setVisible(true);
        activeTablesPanel.revalidate();
        activeTablesPanel.repaint();
        client.sendMessage("TABLE_LIST");
    }

    /** Requests account balance from server **/
    public void requestBalance() {
        client.sendMessage("GET_BALANCE");
    }

    /** Updates displayed balance **/
    public void updateBalanceLabel(String balance) {
        userBalanceLabel.setText("Account Balance: $" + balance);
    }

}
