package frontend.GUIClasses.pages;

import frontend.Client;
import frontend.GUIClasses.styling.BackgroundPanel;
import frontend.GUIClasses.styling.CustomFont;

import javax.swing.*;
import java.awt.*;

public class StartPage {
    /** FIELDS --------------------------------------------------------------------------------------------------- **/
    private final Client client;
    private final CardLayout cardLayout;
    private final JPanel mainPanel;
    private final CustomFont customFont = new CustomFont();
    private JPanel activeTablesPanel;
    private JButton addFundsButton;
    private JLabel userBalanceLabel;
    private JLabel clickRefreshLabel;

    /** CONSTRUCTOR --------------------------------------------------------------------------------------------------- **/
    public StartPage(Client client, CardLayout cardLayout, JPanel mainPanel)
    {
        this.client = client;
        this.cardLayout = cardLayout;
        this.mainPanel = mainPanel;
    }

    /** PAGE BUILDER --------------------------------------------------------------------------------------------------- **/
    public JPanel createStartMenu() {
        // Table Start.png generated by Gemini
        JPanel startPageWrapper = new JPanel(new BorderLayout());
        JPanel wallpaper = new BackgroundPanel("wallpaper.png");
        wallpaper.setPreferredSize(new Dimension(900,800));

        // Table options
        JPanel startMenuPanel = new BackgroundPanel("menu_wallpaper.png");
        startMenuPanel.setLayout(new BoxLayout(startMenuPanel, BoxLayout.Y_AXIS));
        startMenuPanel.setPreferredSize(new Dimension(300,800));
        startMenuPanel.setBackground(Color.WHITE);

        JLabel titleLabel = new JLabel("OTech Blackjack");
        titleLabel.setFont(customFont.bold(25));
        titleLabel.setForeground(new Color(0, 60, 113));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        Dimension buttonSize = new Dimension(220, 40);
        JButton createTableButton = new JButton("Create New Table");
        createTableButton.setFont(customFont.regular(20));
        createTableButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        createTableButton.setPreferredSize(buttonSize);
        createTableButton.setMaximumSize(buttonSize);
        createTableButton.setMinimumSize(buttonSize);
        createTableButton.addActionListener(e ->
        {
            client.sendMessage("NEWTABLE");
        });

        // Live tables list components
        JButton refreshTablesButton = new JButton("Refresh Tables");
        refreshTablesButton.setFont(customFont.regular(20));
        refreshTablesButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        refreshTablesButton.setPreferredSize(buttonSize);
        refreshTablesButton.setMaximumSize(buttonSize);
        refreshTablesButton.setMinimumSize(buttonSize);
        refreshTablesButton.addActionListener(e -> getTableList());

        activeTablesPanel = new JPanel();
        activeTablesPanel.setLayout(new BoxLayout(activeTablesPanel, BoxLayout.Y_AXIS));
        activeTablesPanel.setBackground(Color.WHITE);

        client.sendMessage("TABLELIST");

        clickRefreshLabel = new JLabel("<html><center>No live tables.<br>Please click refresh tables.</center></html>");
        clickRefreshLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        clickRefreshLabel.setHorizontalAlignment(SwingConstants.CENTER);
        clickRefreshLabel.setFont(customFont.regular(20));

        // Account balance management
        userBalanceLabel = new JLabel("Account Balance: ");
        userBalanceLabel.setFont(customFont.bold(20));
        userBalanceLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        addFundsButton = new JButton("Add funds");
        addFundsButton.setFont(customFont.regular(20));
        addFundsButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        addFundsButton.setPreferredSize(buttonSize);
        addFundsButton.setMaximumSize(buttonSize);
        addFundsButton.setMinimumSize(buttonSize);

        addFundsButton.addActionListener(e -> {
            String input = JOptionPane.showInputDialog(mainPanel, "Enter amount to add:", "Add Funds", JOptionPane.PLAIN_MESSAGE);
            if (input != null && !input.trim().isEmpty()) {
                try {
                    int amount = Integer.parseInt(input.trim());
                    if (amount > 0) {
                        client.sendMessage("ADDFUNDS " + amount);
                    } else {
                        JOptionPane.showMessageDialog(mainPanel, "Please enter a valid positive amount.");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(mainPanel, "Invalid amount. Please enter a whole number.");
                }
            }
        });

        startMenuPanel.add(Box.createVerticalStrut(30));
        startMenuPanel.add(titleLabel);

        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(createTableButton);

        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(refreshTablesButton);

        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(activeTablesPanel);

        startMenuPanel.add(Box.createVerticalStrut(200));
        startMenuPanel.add(clickRefreshLabel);
        startMenuPanel.add(Box.createVerticalStrut(200));

        startMenuPanel.add(userBalanceLabel);
        startMenuPanel.add(Box.createVerticalStrut(10));
        startMenuPanel.add(addFundsButton);
        startMenuPanel.add(Box.createVerticalGlue());

        startPageWrapper.add(wallpaper, BorderLayout.WEST);
        startPageWrapper.add(startMenuPanel, BorderLayout.EAST);
        return startPageWrapper;
    }


    /** HELPER METHODS --------------------------------------------------------------------------------------------------- **/
    public void tableList(String data)
    {
        JButton joinButton;
        String[] parts = data.split("\\|");
        if (parts.length < 4)
        {
            return;
        }

        clickRefreshLabel.setVisible(false);
        String tableId = parts[1];
        String numClients = parts[2];
        String hasRoom = parts[3];

        Dimension buttonSize = new Dimension(220, 40);
        joinButton = new JButton("Join Table " + tableId + " (" + numClients + "/3)");
        joinButton.setFont(customFont.regular(20));
        joinButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        joinButton.setPreferredSize(buttonSize);
        joinButton.setMaximumSize(buttonSize);
        joinButton.setMinimumSize(buttonSize);

        joinButton.addActionListener(e -> joinTable(tableId));

        activeTablesPanel.add(joinButton);
        activeTablesPanel.add(Box.createVerticalStrut(10));

        activeTablesPanel.revalidate();
        activeTablesPanel.repaint();

        if (hasRoom.equals("Y"))
        {
            joinButton.setEnabled(true);
        }
        else if(hasRoom.equals("N"))
        {
            joinButton.setEnabled(false);
        }
    }

    // assign client to a table
    public void joinTable(String tableId)
    {
        client.sendMessage("JOINTABLE " + tableId);
    }

    public void getTableList() {
        activeTablesPanel.removeAll();
        activeTablesPanel.revalidate();
        activeTablesPanel.repaint();
        clickRefreshLabel.setVisible(true);
        client.sendMessage("TABLELIST");
    }

    public void requestBalance() {
        client.sendMessage("GET_BALANCE");
    }

    public void updateBalanceLabel(String balance) {
        userBalanceLabel.setText("Account Balance: $" + balance);
    }
}
