package frontend.GUIClasses.Pages;

import frontend.Client;
import frontend.GUIClasses.Styling.BackgroundPanel;
import frontend.GUIClasses.Styling.CustomFont;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class StartPage {
    /** FIELDS --------------------------------------------------------------------------------------------------- **/
    private final Client client;
    private final CardLayout cardLayout;
    private final JPanel mainPanel;
    private final CustomFont customFont = new CustomFont();
    private JPanel activeTablesPanel;

    /** CONSTRUCTOR --------------------------------------------------------------------------------------------------- **/
    public StartPage(Client client, CardLayout cardLayout, JPanel mainPanel)
    {
        this.client = client;
        this.cardLayout = cardLayout;
        this.mainPanel = mainPanel;
    }

    /** PAGE BUILDER --------------------------------------------------------------------------------------------------- **/
    public JPanel createStartMenu() {
        // Table Start.png generated by Gemini
        JPanel startPageWrapper = new JPanel(new BorderLayout());
        JPanel wallpaper = new BackgroundPanel("Table Start.png");
        wallpaper.setPreferredSize(new Dimension(900,800));

        JPanel startMenuPanel = new JPanel();
        startMenuPanel.setLayout(new BoxLayout(startMenuPanel, BoxLayout.Y_AXIS));
        startMenuPanel.setPreferredSize(new Dimension(300,800));

        startMenuPanel.setBackground(Color.WHITE);

        JLabel titleLabel = new JLabel("OTech Blackjack");
        titleLabel.setFont(customFont.bold(25));
        titleLabel.setForeground(new Color(0, 60, 113));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        Dimension buttonSize = new Dimension(220, 40);

        JButton createTableButton = new JButton("Create New Table");
        createTableButton.setFont(customFont.regular(20));
        createTableButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        createTableButton.setPreferredSize(buttonSize);
        createTableButton.setMaximumSize(buttonSize);
        createTableButton.setMinimumSize(buttonSize);
        createTableButton.addActionListener(e ->
        {
            client.sendMessage("NEWTABLE");
        });

        activeTablesPanel = new JPanel();
        activeTablesPanel.setLayout(new BoxLayout(activeTablesPanel, BoxLayout.Y_AXIS));
        activeTablesPanel.setBackground(Color.WHITE);

        startMenuPanel.add(Box.createVerticalStrut(30));
        startMenuPanel.add(titleLabel);

        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(createTableButton);

        startMenuPanel.add(Box.createVerticalStrut(30));
        startMenuPanel.add(activeTablesPanel);
        startMenuPanel.add(Box.createVerticalGlue());

        client.sendMessage("TABLELIST");

        startPageWrapper.add(wallpaper, BorderLayout.WEST);
        startPageWrapper.add(startMenuPanel, BorderLayout.EAST);

        return startPageWrapper;
    }


    /** HELPER METHODS --------------------------------------------------------------------------------------------------- **/
    public void tableList(String data)
    {
        JButton joinButton;
        String[] parts = data.split("\\|");
        if (parts.length < 4)
        {
            return;
        }

        String tableId = parts[1];
        String numClients = parts[2];
        String hasRoom = parts[3];

        Dimension buttonSize = new Dimension(220, 40);
        joinButton = new JButton("Join Table " + tableId + " (" + numClients + "/3)");
        joinButton.setFont(customFont.regular(20));
        joinButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        joinButton.setPreferredSize(buttonSize);
        joinButton.setMaximumSize(buttonSize);
        joinButton.setMinimumSize(buttonSize);

        joinButton.addActionListener(e -> joinTable(tableId));

        activeTablesPanel.add(joinButton);
        activeTablesPanel.add(Box.createVerticalStrut(10));

        activeTablesPanel.revalidate();
        activeTablesPanel.repaint();

        if (hasRoom.equals("Y"))
        {
            joinButton.setEnabled(true);
        }
        else if(hasRoom.equals("N"))
        {
            joinButton.setEnabled(false);
        }
    }

    // assign client to a table
    public void joinTable(String tableId)
    {
        client.sendMessage("JOINTABLE " + tableId);
    }

}
