package frontend.GUIClasses.Pages;

import frontend.Client;
import frontend.GUIClasses.Styling.BackgroundPanel;
import frontend.GUIClasses.Styling.CustomFont;

import javax.swing.*;
import java.awt.*;

public class StartPage {

    // fields
    private final Client client;
    private final CardLayout cardLayout;
    private final JPanel mainPanel;

    public StartPage(Client client, CardLayout cardLayout, JPanel mainPanel)
    {
        this.client = client;
        this.cardLayout = cardLayout;
        this.mainPanel = mainPanel;
    }

    public JPanel createStartMenu() {
        // Table Start.png generated by Gemini
        BackgroundPanel backgroundPanel = new BackgroundPanel("Table Start.png");
        backgroundPanel.setLayout(new GridBagLayout());

        JPanel menuPanel = new JPanel();
        menuPanel.setPreferredSize(new Dimension(350, 200));
        menuPanel.setLayout(new BoxLayout(menuPanel, BoxLayout.Y_AXIS));
        menuPanel.setBackground(new Color(0, 0, 0, 170));

        JLabel titleLabel = new JLabel("OTech Blackjack");
        titleLabel.setFont(CustomFont.newFont(25));
        titleLabel.setForeground(new Color(212, 175, 55));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JButton joinGameButton = new JButton("Join Table");

        joinGameButton.setFont(CustomFont.newFont(25));

        joinGameButton.setAlignmentX(Component.CENTER_ALIGNMENT);

        joinGameButton.setMaximumSize(new Dimension(220, 45));

        joinGameButton.addActionListener(e ->
        {
            cardLayout.show(mainPanel, "game");
            client.sendMessage("JOIN admin");
            client.sendMessage("START");
        });

        menuPanel.add(Box.createVerticalStrut(30));
        menuPanel.add(titleLabel);
        menuPanel.add(Box.createVerticalStrut(20));
        menuPanel.add(joinGameButton);
        menuPanel.add(Box.createVerticalGlue());

        backgroundPanel.add(menuPanel);

        return backgroundPanel;
    }


}
