package frontend.GUIClasses.Pages;

import frontend.Client;
import frontend.GUIClasses.Styling.BackgroundPanel;
import frontend.GUIClasses.Styling.CustomFont;

import javax.swing.*;
import java.awt.*;

public class StartPage {

    // fields
    private final Client client;
    private final CardLayout cardLayout;
    private final JPanel mainPanel;
    private final CustomFont customFont = new CustomFont();

    public StartPage(Client client, CardLayout cardLayout, JPanel mainPanel)
    {
        this.client = client;
        this.cardLayout = cardLayout;
        this.mainPanel = mainPanel;
    }

    public JPanel createStartMenu() {
        // Table Start.png generated by Gemini
        JPanel startPageWrapper = new JPanel(new BorderLayout());
        JPanel wallpaper = new BackgroundPanel("Table Start.png");
        wallpaper.setPreferredSize(new Dimension(900,800));

        JPanel startMenuPanel = new JPanel();
        startMenuPanel.setLayout(new BoxLayout(startMenuPanel, BoxLayout.Y_AXIS));
        startMenuPanel.setPreferredSize(new Dimension(300,800));

        startMenuPanel.setBackground(Color.WHITE);


        JLabel titleLabel = new JLabel("OTech Blackjack");
        titleLabel.setFont(customFont.bold(25));
        titleLabel.setForeground(new Color(212, 175, 55));
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JButton joinGameButton = new JButton("Create New Table");
        joinGameButton.setFont(customFont.regular(25));
        joinGameButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        joinGameButton.setMaximumSize(new Dimension(220, 45));
        joinGameButton.addActionListener(e ->
        {
            cardLayout.show(mainPanel, "game");
            client.sendMessage("START");
        });

        startMenuPanel.add(Box.createVerticalStrut(30));
        startMenuPanel.add(titleLabel);
        startMenuPanel.add(Box.createVerticalStrut(20));
        startMenuPanel.add(joinGameButton);
        startMenuPanel.add(Box.createVerticalGlue());

        startPageWrapper.add(wallpaper, BorderLayout.WEST);
        startPageWrapper.add(startMenuPanel, BorderLayout.EAST);

        return startPageWrapper;
    }


}
